### ISSUE TITLE
compile-time constants for LIBXSMM_GEMM_DESCRIPTOR macro result into warnings/errors

### ISSUE THREAD

**Issue by alheinecke** [hfp/libxsmm#84]
consider the following code in test.c:

<code>
#include <libxsmm.h>

int main(int argc, char* argv[]) {
  libxsmm_gemm_descriptor l_xgemm_desc;
  LIBXSMM_GEMM_DESCRIPTOR(l_xgemm_desc, 1, 0,
    16, 16, 16, 16, 16, 16,
    1, 0, 0);
  
  LIBXSMM_GEMM_DESCRIPTOR(l_xgemm_desc, 1, 0,
    16, 16, 16, 16, 16, 16,
    1.0, 0.0, 0);

  LIBXSMM_GEMM_DESCRIPTOR(l_xgemm_desc, 1, 0,
    16, 16, 16, 16, 16, 16,
    0, 1, 0);

  LIBXSMM_GEMM_DESCRIPTOR(l_xgemm_desc, 1, 0,
    16, 16, 16, 16, 16, 16,
    0.0, 1.0, 0);
  
LIBXSMM_GEMM_DESCRIPTOR(l_xgemm_desc, 1, 0,
    16, 16, 16, 16, 16, 16,
    1, 1, 0);

  LIBXSMM_GEMM_DESCRIPTOR(l_xgemm_desc, 1, 0,
    16, 16, 16, 16, 16, 16,
    1.0, 1.0, 0);

  return 0;
}
</code>

If I compile this with ICC 16.0.3, I see warning when alpha/beta are zero:
icc -O2 -ansi-alias -xMIC-AVX512 test.c -$LIBXSMM_INC -L$LIBXSMM_LIB -lxsmm -lpthread -mkl -o test
libxsmm_test.c(5): warning #173: floating-point value does not fit in required integral type
    LIBXSMM_GEMM_DESCRIPTOR(l_xgemm_desc, 1, 0,
    ^

libxsmm_test.c(9): warning #173: floating-point value does not fit in required integral type
    LIBXSMM_GEMM_DESCRIPTOR(l_xgemm_desc, 1, 0,
    ^

libxsmm_test.c(13): warning #173: floating-point value does not fit in required integral type
    LIBXSMM_GEMM_DESCRIPTOR(l_xgemm_desc, 1, 0,
    ^

libxsmm_test.c(17): warning #173: floating-point value does not fit in required integral type
    LIBXSMM_GEMM_DESCRIPTOR(l_xgemm_desc, 1, 0,

**Comment by breuera** [comment]
```
#include <libxsmm.h>

int main(int argc, char* argv[]) { libxsmm_gemm_descriptor l_xgemm_desc; LIBXSMM_GEMM_DESCRIPTOR(l_xgemm_desc, 1, 0, 16, 16, 16, 16, 16, 16, 1, 0, 0);

LIBXSMM_GEMM_DESCRIPTOR(l_xgemm_desc, 1, 0, 16, 16, 16, 16, 16, 16, 1.0, 0.0, 0);

LIBXSMM_GEMM_DESCRIPTOR(l_xgemm_desc, 1, 0, 16, 16, 16, 16, 16, 16, 0, 1, 0);

LIBXSMM_GEMM_DESCRIPTOR(l_xgemm_desc, 1, 0, 16, 16, 16, 16, 16, 16, 0.0, 1.0, 0);

LIBXSMM_GEMM_DESCRIPTOR(l_xgemm_desc, 1, 0, 16, 16, 16, 16, 16, 16, 1, 1, 0);

LIBXSMM_GEMM_DESCRIPTOR(l_xgemm_desc, 1, 0, 16, 16, 16, 16, 16, 16, 1.0, 1.0, 0);

return 0; }

```

gives

```
alex@alex-OptiPlex-9020 ~/tst $ clang-3.6 --version
Ubuntu clang version 3.6.0-2ubuntu1~trusty1 (tags/RELEASE_360/final) (based on LLVM 3.6.0)
Target: x86_64-pc-linux-gnu
Thread model: posix
alex@alex-OptiPlex-9020 ~/tst $ clang-3.6 test.c -Ilibxsmm/include/ -lxsmm -Llibxsmm/lib/ OpenBLAS/libopenblas.a -fopenmp
alex@alex-OptiPlex-9020 ~/tst $ ./
a.out     libxsmm/  OpenBLAS/ 
alex@alex-OptiPlex-9020 ~/tst $ ./a.out
```

```
alex@alex-OptiPlex-9020 ~/tst $ gcc --version
gcc (Ubuntu 4.8.5-2ubuntu1~14.04.1) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

alex@alex-OptiPlex-9020 ~/tst $ gcc test.c -Ilibxsmm/include/ -lxsmm -Llibxsmm/lib/ OpenBLAS/libopenblas.a -fopenmp
In file included from libxsmm/include/libxsmm_frontend.h:51:0,
                 from libxsmm/include/libxsmm.h:66,
                 from test.c:1:
test.c: In function ‘main’:
libxsmm/include/libxsmm_generator.h:57:75: warning: division by zero [-Wdiv-by-zero]
       if (0 < (BETA) || 0 > (BETA)) (DESCRIPTOR).beta = (signed char)(1.0 / (BETA)); \
                                                                           ^
libxsmm/include/libxsmm_generator.h:92:3: note: in expansion of macro ‘LIBXSMM_GEMM_DESCRIPTOR_FIXUP’
   LIBXSMM_GEMM_DESCRIPTOR_FIXUP(DESCRIPTOR, FLAGS, ALPHA, BETA)
   ^
test.c:3:74: note: in expansion of macro ‘LIBXSMM_GEMM_DESCRIPTOR’
 int main(int argc, char* argv[]) { libxsmm_gemm_descriptor l_xgemm_desc; LIBXSMM_GEMM_DESCRIPTOR(l_xgemm_desc, 1, 0, 16, 16, 16, 16, 16, 16, 1, 0, 0);
                                                                          ^
libxsmm/include/libxsmm_generator.h:54:78: warning: division by zero [-Wdiv-by-zero]
       if (0 < (ALPHA) || 0 > (ALPHA)) (DESCRIPTOR).alpha = (signed char)(1.0 / (ALPHA)); \
                                                                              ^
libxsmm/include/libxsmm_generator.h:92:3: note: in expansion of macro ‘LIBXSMM_GEMM_DESCRIPTOR_FIXUP’
   LIBXSMM_GEMM_DESCRIPTOR_FIXUP(DESCRIPTOR, FLAGS, ALPHA, BETA)
   ^
test.c:7:1: note: in expansion of macro ‘LIBXSMM_GEMM_DESCRIPTOR’
 LIBXSMM_GEMM_DESCRIPTOR(l_xgemm_desc, 1, 0, 16, 16, 16, 16, 16, 16, 0, 1, 0);
 ^
alex@alex-OptiPlex-9020 ~/tst
```

```
alex@alex-OptiPlex-9020 ~/tst $ gcc-4.9 --version
gcc-4.9 (Ubuntu 4.9.3-8ubuntu2~14.04) 4.9.3
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

alex@alex-OptiPlex-9020 ~/tst $ gcc-4.9 test.c -Ilibxsmm/include/ -lxsmm -Llibxsmm/lib/ OpenBLAS/libopenblas.a -fopenmp
In file included from libxsmm/include/libxsmm_frontend.h:51:0,
                 from libxsmm/include/libxsmm.h:66,
                 from test.c:1:
test.c: In function ‘main’:
libxsmm/include/libxsmm_generator.h:57:75: warning: division by zero [-Wdiv-by-zero]
       if (0 < (BETA) || 0 > (BETA)) (DESCRIPTOR).beta = (signed char)(1.0 / (BETA)); \
                                                                           ^
libxsmm/include/libxsmm_generator.h:92:3: note: in expansion of macro ‘LIBXSMM_GEMM_DESCRIPTOR_FIXUP’
   LIBXSMM_GEMM_DESCRIPTOR_FIXUP(DESCRIPTOR, FLAGS, ALPHA, BETA)
   ^
test.c:3:74: note: in expansion of macro ‘LIBXSMM_GEMM_DESCRIPTOR’
 int main(int argc, char* argv[]) { libxsmm_gemm_descriptor l_xgemm_desc; LIBXSMM_GEMM_DESCRIPTOR(l_xgemm_desc, 1, 0, 16, 16, 16, 16, 16, 16, 1, 0, 0);
                                                                          ^
libxsmm/include/libxsmm_generator.h:54:78: warning: division by zero [-Wdiv-by-zero]
       if (0 < (ALPHA) || 0 > (ALPHA)) (DESCRIPTOR).alpha = (signed char)(1.0 / (ALPHA)); \
                                                                              ^
libxsmm/include/libxsmm_generator.h:92:3: note: in expansion of macro ‘LIBXSMM_GEMM_DESCRIPTOR_FIXUP’
   LIBXSMM_GEMM_DESCRIPTOR_FIXUP(DESCRIPTOR, FLAGS, ALPHA, BETA)
   ^
test.c:7:1: note: in expansion of macro ‘LIBXSMM_GEMM_DESCRIPTOR’
 LIBXSMM_GEMM_DESCRIPTOR(l_xgemm_desc, 1, 0, 16, 16, 16, 16, 16, 16, 0, 1, 0);
 ^
alex@alex-OptiPlex-9020 ~/tst
```

**Comment by hfp** [comment]
Resolved by 5837b8e.

**Comment by alheinecke** [comment]
I'm still seeing this issue with the current master and ICC 16.0.3

**Comment by hfp** [comment]
I have the exact same compiler but couldn't reproduce. The only thing left was when compiling the test case as C++ translation unit. Anyhow, I've removed support for fractional Alpha and Beta, which likely caused the issue in the "fixup" phase of building the descriptor.

Can you check if it's resolved?

**Comment by alheinecke** [comment]
Now it's fixed (and it was C++ code). It seemed it was implicit conversion...

The fix was to pass static_cast<double>1.0, static_cast<double>0.0, but now it's also working with 1, 0
